// Abbreviation expansion dictionary & normalization rules for The Moderator

export const SUBJECT_ABBREVIATIONS: Record<string, string> = {
  eng: "ENGLISH LANGUAGE",
  "eng lang": "ENGLISH LANGUAGE",
  "eng.": "ENGLISH LANGUAGE",
  english: "ENGLISH LANGUAGE",
  math: "MATHEMATICS",
  maths: "MATHEMATICS",
  mth: "MATHEMATICS",
  "math.": "MATHEMATICS",
  mathematics: "MATHEMATICS",
  gov: "GOVERNMENT",
  govt: "GOVERNMENT",
  "gov.": "GOVERNMENT",
  "govt.": "GOVERNMENT",
  government: "GOVERNMENT",
  bio: "BIOLOGY",
  biol: "BIOLOGY",
  "bio.": "BIOLOGY",
  biology: "BIOLOGY",
  chem: "CHEMISTRY",
  chm: "CHEMISTRY",
  "chem.": "CHEMISTRY",
  chemistry: "CHEMISTRY",
  phy: "PHYSICS",
  phys: "PHYSICS",
  "phy.": "PHYSICS",
  physics: "PHYSICS",
  econs: "ECONOMICS",
  econ: "ECONOMICS",
  "econs.": "ECONOMICS",
  economics: "ECONOMICS",
  geo: "GEOGRAPHY",
  geog: "GEOGRAPHY",
  "geo.": "GEOGRAPHY",
  geography: "GEOGRAPHY",
  civic: "CIVIC EDUCATION",
  "civic edu": "CIVIC EDUCATION",
  "civic education": "CIVIC EDUCATION",
  crk: "CHRISTIAN RELIGIOUS STUDIES",
  crs: "CHRISTIAN RELIGIOUS STUDIES",
  "c.r.k": "CHRISTIAN RELIGIOUS STUDIES",
  "c.r.s": "CHRISTIAN RELIGIOUS STUDIES",
  irk: "ISLAMIC RELIGIOUS STUDIES",
  irs: "ISLAMIC RELIGIOUS STUDIES",
  "i.r.k": "ISLAMIC RELIGIOUS STUDIES",
  "i.r.s": "ISLAMIC RELIGIOUS STUDIES",
  agric: "AGRICULTURAL SCIENCE",
  "agric sci": "AGRICULTURAL SCIENCE",
  "agric.": "AGRICULTURAL SCIENCE",
  "agricultural science": "AGRICULTURAL SCIENCE",
  comm: "COMMERCE",
  commerce: "COMMERCE",
  "comm.": "COMMERCE",
  acc: "FINANCIAL ACCOUNTING",
  acct: "FINANCIAL ACCOUNTING",
  accounting: "FINANCIAL ACCOUNTING",
  accounts: "FINANCIAL ACCOUNTING",
  lit: "LITERATURE IN ENGLISH",
  "lit in eng": "LITERATURE IN ENGLISH",
  literature: "LITERATURE IN ENGLISH",
  "basic tech": "BASIC TECHNOLOGY",
  "b.tech": "BASIC TECHNOLOGY",
  "b tech": "BASIC TECHNOLOGY",
  "basic sci": "BASIC SCIENCE",
  "b.sci": "BASIC SCIENCE",
  "b sci": "BASIC SCIENCE",
  sos: "SOCIAL STUDIES",
  "social studies": "SOCIAL STUDIES",
  "soc studies": "SOCIAL STUDIES",
  phe: "PHYSICAL AND HEALTH EDUCATION",
  "p.h.e": "PHYSICAL AND HEALTH EDUCATION",
  "p.h.e.": "PHYSICAL AND HEALTH EDUCATION",
  cca: "CULTURAL AND CREATIVE ARTS",
  "c.c.a": "CULTURAL AND CREATIVE ARTS",
  comp: "COMPUTER STUDIES",
  "comp.": "COMPUTER STUDIES",
  ict: "INFORMATION AND COMMUNICATION TECHNOLOGY",
  "computer studies": "COMPUTER STUDIES",
  "home econs": "HOME ECONOMICS",
  "home econ": "HOME ECONOMICS",
  "home economics": "HOME ECONOMICS",
  hausa: "HAUSA LANGUAGE",
  arabic: "ARABIC LANGUAGE",
  yoruba: "YORUBA LANGUAGE",
  igbo: "IGBO LANGUAGE",
  french: "FRENCH LANGUAGE",
  "f/maths": "FURTHER MATHEMATICS",
  "further maths": "FURTHER MATHEMATICS",
  "further mathematics": "FURTHER MATHEMATICS",
  "bus studies": "BUSINESS STUDIES",
  "bus. studies": "BUSINESS STUDIES",
  "business studies": "BUSINESS STUDIES",
  history: "HISTORY",
  data: "DATA PROCESSING",
  "data processing": "DATA PROCESSING",
  marketing: "MARKETING",
  insurance: "INSURANCE",
  technical: "TECHNICAL DRAWING",
  "tech drawing": "TECHNICAL DRAWING",
  "t.d": "TECHNICAL DRAWING",
};

export const CLASS_LEVEL_MAP: Record<string, string> = {
  "j.s.s 1": "JSS 1",
  "j.s.s. 1": "JSS 1",
  "jss 1": "JSS 1",
  "jss1": "JSS 1",
  "js 1": "JSS 1",
  "js1": "JSS 1",
  "j.s.s 2": "JSS 2",
  "j.s.s. 2": "JSS 2",
  "jss 2": "JSS 2",
  "jss2": "JSS 2",
  "js 2": "JSS 2",
  "js2": "JSS 2",
  "j.s.s 3": "JSS 3",
  "j.s.s. 3": "JSS 3",
  "jss 3": "JSS 3",
  "jss3": "JSS 3",
  "js 3": "JSS 3",
  "js3": "JSS 3",
  "j.s.s": "JSS",
  "jss": "JSS",
  "js": "JSS",

  "s.s.s 1": "SSS 1",
  "s.s.s. 1": "SSS 1",
  "sss 1": "SSS 1",
  "sss1": "SSS 1",
  "ss 1": "SSS 1",
  "ss1": "SSS 1",
  "s.s 1": "SSS 1",
  "s.s.s 2": "SSS 2",
  "s.s.s. 2": "SSS 2",
  "sss 2": "SSS 2",
  "sss2": "SSS 2",
  "ss 2": "SSS 2",
  "ss2": "SSS 2",
  "s.s 2": "SSS 2",
  "s.s.s 3": "SSS 3",
  "s.s.s. 3": "SSS 3",
  "sss 3": "SSS 3",
  "sss3": "SSS 3",
  "ss 3": "SSS 3",
  "ss3": "SSS 3",
  "s.s 3": "SSS 3",
  "s.s.s": "SSS",
  "sss": "SSS",
  "ss": "SSS",
  "s.s": "SSS",
  "pri 1": "PRIMARY 1",
  "pri 2": "PRIMARY 2",
  "pri 3": "PRIMARY 3",
  "pri 4": "PRIMARY 4",
  "pri 5": "PRIMARY 5",
  "pri 6": "PRIMARY 6",
  "pry 1": "PRIMARY 1",
  "pry 2": "PRIMARY 2",
  "pry 3": "PRIMARY 3",
  "pry 4": "PRIMARY 4",
  "pry 5": "PRIMARY 5",
  "pry 6": "PRIMARY 6",
};

export const COMMON_TYPOS_MAP: Record<string, string> = {
  "the(A)": "the (A)",
  "called(A)": "called (A)",
  "is(A)": "is (A)",
  "a(A)": "a (A)",
  "to(A)": "to (A)",
  "if they(A)": "if they (A)",
  "it(A)": "it (A)",
  "media?(A)": "media? (A)",
  "Nigeria?(A)": "Nigeria? (A)",
  "received is(A)": "received is (A)",
  "del": "(d) dismissal",
  "byelection": "by-election",
  "by election": "by-election",
  "Firstpast-the-post": "First-past-the-post",
  "First past the post": "First-past-the-post",
};
